trigger:
- master

variables:
  gh_name: Eric J. Ma
  gh_pass: $(github_pat)
  gh_email: $(github_email)
  gh_auth_header: $(echo -n "${gh_user}:$(gh_pass)" | base64);

jobs:
- job:
  displayName: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  # Install an SSH key prior to a build or deployment
  - task: DownloadSecureFile@1
    inputs:
      secureFile: gh_key
    displayName: 'Get the deploy key'

  - script: |
      mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
      chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    displayName: 'Setup SSH keys'

  - bash: git clone git@github.com:ericmjl/essays-on-data-science.git
    workingDirectory: $(Build.StagingDirectory)
    displayName: "[Git] Clone GitHub Pages Repository"

  # - script: |
  #     git config user.email $(gh_email)
  #     git config user.name $(gh_user)
  #   workingDirectory: $(Build.StagingDirectory)
  #   displayName: '[Git] Configure User'

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda env create -f environment.yml
    displayName: Create conda environment

  - bash: |
      source activate essays-on-data-science
      pre-commit install
    displayName: Install pre-commit

  - bash: |
      source activate essays-on-data-science
      # git config user.email $(gh_email)
      # git config user.name $(gh_user)
      make deploy
    workingDirectory: $(Build.StagingDirectory)
    displayName: Deploy docs to GitHub pages
