trigger:
- master

jobs:
- job:
  displayName: Linux
  pool:
    vmImage: 'ubuntu-16.04'

variables:
  gh_user: ericmjl
  gh_repo: essays-on-data-science
  gh_pass: $(github_pat)
  gh_email: $(github_email)
  gh_auth_header: $(echo -n "${gh_user}:$(gh_pass)" | base64);


steps:
  - bash: git clone https://$(gh_pass)@github.com/$(gh_user)/$(gh_repo).git .
    workingDirectory: $(Build.StagingDirectory)
    displayName: "[Git] Clone GitHub Pages Repository"

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda env create -f environment.yml
    displayName: Create conda environment

  - bash: |
      source activate essays-on-data-science
      pre-commit install
    displayName: Install pre-commit

  - bash: |
      source activate essays-on-data-science
      make deploy
    displayName: Deploy docs to GitHub pages
