site_name: Essays on Data Science
nav:
  - Home: index.md
  - Software Skills:
    - Introduction: software-skills/index.md
    - Refactoring: software-skills/refactoring.md
    - Documentation: software-skills/documentation.md
    - Testing: software-skills/testing.md
theme:
  name: 'material'

# Taken from here: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
markdown_extensions:
  - codehilite
