site_name: Essays on Data Science
theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo:
    icon: 'library_books'

plugins:
  - search

# Taken from here: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
markdown_extensions:
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

google_analytics:
  - 'UA-12498603-3'
  - 'auto'

repo_name: 'ericmjl/essays-on-data-science'
repo_url: 'https://github.com/ericmjl/essays-on-data-science'

extra:
  social:
    - type: 'envelope'
      link: 'http://www.shortwhale.com/ericmjl'
    - type: 'github'
      link: 'https://github.com/ericmjl'
    - type: 'twitter'
      link: 'https://twitter.com/ericmjl'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/ericmjl'
